export const Tracks = [
    {
        id: 1,
        url: '../assets/media/track.mp3',
        title: 'Korobeiniki 1',
        artist: 'Tetris',
        album: 'Tetris Theme',
        genre: 'Games',
        date: '2014-05-20T07:00:00+00:00',
        artwork: '../assets/images/react-native-logo.png',
    },
    {
        id: 2,
        url: '../assets/media/track.mp3',
        title: 'Korobeiniki 2',
        artist: 'Tetris',
        album: 'Tetris Theme',
        genre: 'Games',
        date: '2014-05-20T07:00:00+00:00',
        artwork: '../assets/images/react-native-logo.png',
    },
    {
        id: 3,
        url: '../assets/media/track.mp3',
        title: 'Korobeiniki 3',
        artist: 'Tetris',
        album: 'Tetris Theme',
        genre: 'Games',
        date: '2014-05-20T07:00:00+00:00',
        artwork: '../assets/images/react-native-logo.png',
    },
]